Workflow Best Practices naming conventions draft
galaxyproject/iwc pull request #12
Opened 2018-11-02 18:56 UTC by tshtatland

Add Galaxy Workflow Best Practices naming conventions draft.
Intended audience: internal and external Galaxy workflow developers, maintainers, and users.

- The style is easy for the reader and maintainer.
- Look and feel is consistent with a very popular, influential and respected book "Perl Best Practices" by Damian Conway.

Add Galaxy Workflow Best Practices to README

- Short description: what they are and what they are not. Hopefully, should help prevent flame wars.
- Add references and sources.

2018-11-02 20:42 UTC, bgruening commented
Cool thanks @tshtatland for working on this!

2022-11-05 14:28 UTC, bwlang approved these changes
I just found this PR - it's old but I think this is still helpful

2022-11-06 15:57 UTC, mvdbeek requested changes
Thanks @tshtatland @bgruening,

I like the idea of providing full analysis details, we could start with a public history of an example run, however I wouldn't make that mandatory. Putting the meeting notes and calendar in a more public spot is also a good idea. Otherwise I think that the contributing document is not too bad for getting started. I would say adding relevant bits to the existing documentation is probably the right way to do ? 

I hope I'll see you at the next IWC meeting!

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> +## This group exists to create a registry of community workflows.
I like the current readme more, it is short and to the point.

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> + - help scientists find workflows!
That's redundant with the contributing document.

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> +   - downsampled data (validity of workflow results)
I agree that we should have some example analysis with the full details, but we're not there yet. The rest is again redundant with the contributing document

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> + - if linting passes, tests pass, and human review passes, PR is merged and added to registry list
it's all in the contributing document

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> + * [the notes](https://github.com/galaxyproject/iwc/issues/3) from the initial meeting at GCCBOSC2018 CoFest
meeting minutes are attached to the google calendar, linking them up would be a good idea.

2022-11-06 15:57 UTC, mvdbeek commented on README.md
> +## Galaxy Workflow Best Practices
This section is partially redundant with https://planemo.readthedocs.io/en/latest/best_practices_workflows.html which we link to, and partially not relevant.

2022-11-06 15:57 UTC, mvdbeek commented on best_practices/01_reference_guide.md
> +## Naming Conventions
Good to have this, but these are not our current naming conventions, they are however outlined in the contributing document

2022-11-06 15:57 UTC, mvdbeek commented on best_practices/01_reference_guide.md
> +## Naming Conventions
Overall it's unclear who the audience is for this document.

2022-11-06 15:57 UTC, mvdbeek commented on best_practices/naming_conventions.md
> +# Naming Conventions
This is way too long, most of it is enforced anyway by github conventions.

2022-11-06 15:57 UTC, mvdbeek commented on best_practices/running_workflows.md
> +### Keep records of the workflows, inputs and parameters.
All of that is recorded in Galaxy, does this maybe date from many years back when it wasn't in the user interface ?

2022-11-06 15:57 UTC, mvdbeek commented on best_practices/workflows_misc.md
> +## Citing
Citation information is embedded everywhere, in the Galaxy workflow, in dockstore/workflowhub etc, I don't think this is necessary to repeat here.

2024-06-29 12:09 UTC, closed without merging